### ISSUE TITLE
include fix is required for arch linux users

### ISSUE THREAD

**Issue by jose1711** [shugaa/florb#2]
don't know the reason but this is needed for arch linux users to be able to compile florb:
```
sed -i '/^#include/s%Fl/%FL/%' dlg_ui_ex.cpp dlg_settings_ex.cpp
```
full PKGBUILD available at https://aur.archlinux.org/packages/florb-git/

**Comment by shugaa** [comment]
Well, that's probably because Archs FLTK install does not create a symlink from include/Fl to include/FL to cover sloppy programming:)  On my Fedora for example it looks like this: 

```
$ file /usr/include/Fl
/usr/include/Fl: symbolic link to FL
```

include/FL seems to be the proper way to go though. I'm a little short on time right now but I'll go about fixing this as soon as I can. Or you might create a patch yourself if you're in a hurry.

Thanks for reporting!
